# Generated by Django 4.0.7 on 2022-09-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='service',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
        migrations.AddField(
            model_name='service',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
    ]
