# Generated by Django 4.0.7 on 2022-10-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
