# Generated by Django 4.0.7 on 2022-10-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_gallerypicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypicks',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
