# Generated by Django 4.0.7 on 2022-09-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sisis_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sisisuser',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='groups'),
        ),
    ]
