# Generated by Django 4.0.4 on 2022-05-28 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisis_auth', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+34000000000'. Exactly 11 digits allowed.", regex='^[\\+][3][4][0-9]{9}$')]),
        ),
    ]
