# Generated by Django 4.0.7 on 2022-10-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisis_auth', '0003_profile_social_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_links',
            new_name='fb_link',
        ),
        migrations.AddField(
            model_name='profile',
            name='insta_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tweeter_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vimeo_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
