# Generated by Django 4.0.4 on 2022-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisis_auth', '0004_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sisisuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
