# Generated by Django 4.0.2 on 2022-06-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisis_auth', '0006_alter_sisisuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sisisuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
