# Generated by Django 4.0.2 on 2022-06-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('shopping_app', '0003_alter_order_items'),
        ('blog_app', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sisis_auth', '0008_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SisisUser',
            new_name='SiteUser',
        ),
    ]
