# Generated by Django 4.0.2 on 2022-06-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shopping_app', '0003_alter_order_items'),
        ('blog_app', '0002_initial'),
        ('sisis_auth', '0009_rename_sisisuser_siteuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteUser',
            new_name='SisisUser',
        ),
    ]
