# Generated by Django 4.0.7 on 2022-09-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
