# Generated by Django 4.0.7 on 2022-09-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
    ]
