# Generated by Django 4.0.7 on 2022-09-18 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_alter_product_options_alter_shippingaddress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.CharField(default=datetime.datetime(2022, 9, 18, 13, 13, 18, 526973, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 9, 18, 13, 15, 46, 98791, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default=datetime.datetime(2022, 9, 18, 13, 15, 54, 587494, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
