# Generated by Django 4.0.7 on 2022-10-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisis_auth', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_links',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
