# Generated by Django 4.0.7 on 2022-10-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisis_auth', '0004_rename_social_links_profile_fb_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='insta_link',
            new_name='link_link',
        ),
    ]
