# Generated by Django 4.0.2 on 2022-05-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
