# Generated by Django 4.0.2 on 2022-08-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters_app', '0004_alter_newsletteruser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created']},
        ),
    ]
