# Generated by Django 4.0.2 on 2022-08-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters_app', '0005_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=models.TextField(max_length=3200, verbose_name="Markdown's Content"),
        ),
    ]
